CHANGE REPLICATION SOURCE TO SOURCE_HOST='master', SOURCE_PORT=3306, SOURCE_USER='repl', SOURCE_PASSWORD='password', source_ssl = 1, SOURCE_AUTO_POSITION=1;
START REPLICA;

-- user名 userにREAD ONLY権限を不要する
GRANT SELECT, PROCESS, SHOW DATABASES ON *.* TO 'user'@'%';




